### ISSUE TITLE
Support Jest 25

### ISSUE THREAD

**Issue by mschnee** [jest-community/jest-junit#121]
Using jest-junit as the only reporter
```json
{
  "coverageReporters": ["jest-junit"],
}
```

The following error is printed
```
        Failed to write coverage reports:
        ERROR: TypeError: _istanbulReports(...).default.create(...).execute is not a function
        STACK: TypeError: _istanbulReports(...).default.create(...).execute is not a function
    at /workspaces/api/node_modules/@jest/reporters/build/coverage_reporter.js:303:12
    at Array.forEach (<anonymous>)
    at CoverageReporter.onRunComplete (/workspaces/api/node_modules/@jest/reporters/build/coverage_reporter.js:298:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ReporterDispatcher.onRunComplete (/workspaces/api/node_modules/@jest/core/build/ReporterDispatcher.js:71:10)
    at async TestScheduler.scheduleTests (/workspaces/api/node_modules/@jest/core/build/TestScheduler.js:280:5)
    at async runJest (/workspaces/api/node_modules/@jest/core/build/runJest.js:414:19)
    at async _run (/workspaces/api/node_modules/@jest/core/build/cli/index.js:371:7)
    at async runCLI (/workspaces/api/node_modules/@jest/core/build/cli/index.js:224:3)
    at async Object.run (/workspaces/api/node_modules/jest-cli/build/cli/index.js:216:37)
```

This does not occur with other reporters:
```json
{
  "coverageReporters": ["text-summary", "lcov"],
}
```

**Comment by palmerj3** [comment]
Hey thanks for submitting an issue!

jest-junit is not a coverage reporter. It's just a reporter.

If you replace "coverageReporters" with "reporters" does it work?

**Comment by mschnee** [comment]
Good question!  I'll give it a try.

**Comment by mschnee** [comment]
Apparently it does :+1:
