### ISSUE TITLE
Cannot find module 'react' from 'index.js' - (node_modules/jest-resolve/build/index.js:259:17)

### ISSUE THREAD

**Issue by cdhit** [jest-community/jest-junit#149]
My project creation process (this is a `create-react-app` typescript version template: 
```
  25 npx create-react-app test --template typescript
  26 cd test
  27 ls
  28 npm install --save-dev react-test-renderer
  29 npm test
  30 npm test
  31 node --version
  32 npx create-react-app --version
  33 npm install antd -g
  34 npm test
```

My `Jest` version in package-lock.json
```
    "@jest/core": {
      "version": "24.9.0",
```

My node.js version is 
```
v12.19.0
```

create-react-app version is
```
npx create-react-app --version
3.4.1
```

antd version is
```
antd@4.6.6
```

file: App.test.tsx `testing file`
```
import React from 'react';
import { render } from '@testing-library/react';
import App from './App';
import renderer from 'react-test-renderer';
import MyButton from './components/button';


it('renders a snapshot', () => {
  const tree = renderer.create(<App/>).toJSON();
  expect(tree).toMatchSnapshot();
});


it('MyButton', () => {
  const tree = renderer.create(<MyButton/>).toJSON();
  expect(tree).toMatchSnapshot();
});
```

My `antd` source file
```
import React from 'react'
import { Button } from 'antd';

const MyButton = () => {
  const [value, setValue] = React.useState('')

  // The event type is a "ChangeEvent"
  // We pass in "HTMLInputElement" to the input
  function onChange(e: React.ChangeEvent<HTMLInputElement>) {
    setValue(e.target.value)
  }

  return <Button></Button>
}

export default MyButton;
```

When I ran `npm test`, I got this 
```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Cannot find module 'react' from 'index.js'

    However, Jest was able to find:
        'components/button.tsx'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../../../node_modules/antd/lib/affix/index.js:26:37)
```

**Comment by palmerj3** [comment]
This issue has nothing to do with jest-junit. Please try stackoverflow.
