### ISSUE TITLE
Invalid XML produced if an error message contains an ESC character (0x1B)

### ISSUE THREAD

**Issue by asztal** [jest-community/jest-junit#197]
To reproduce the issue:
```js
test("breaks jest-junit", () => {
    throw new Error("\x1b");
});
```

For example, this can be produced by the `@testing-library/react` when it decides the summary of the DOM is too long and truncates it (as it may happen to truncate the text in the middle of an ANSI escape code, meaning `strip-ansi` won't remove it).

The output is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="1" failures="1" errors="0" time="2">
  <testsuite name="undefined" errors="0" failures="1" skipped="0" timestamp="2022-01-25T12:11:51" time="1.561" tests="1">
    <testcase classname=" breaks jest-junit" name=" breaks jest-junit" time="0.001">
      <failure>Error: 
    at Object.&lt;anonymous&gt; (/home/lee/project/src/junit.spec.ts:2:11)
    at Object.asyncJestTest (/home/lee/project/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /home/lee/project/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/home/lee/project/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /home/lee/project/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
  </testsuite>
</testsuites>
```

This is invalid XML and makes it harder to see why the test failed since Azure DevOps rejects the junit.xml file.

**Comment by palmerj3** [comment]
Thank you!

Could you please create a repo that reproduces this issue? Then i'd be happy to have a look.

**Comment by cc-ebay** [comment]
It is pretty straightforward how to reproduce it.  The output in the XML should filter out an ESC characters sequences
