### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by alons1** [jest-community/jest-junit#248]
I'm getting this error when trying to use the reporter.
I'm on Node v16.19.1
Latest jest-junit

`Error [ERR_REQUIRE_ESM]: require() of ES Module C:\work\Builder\MyProject\node_modules\ansi-regex\index.js from C:\work\Builder\MyProject\node_modules\strip-ansi\index.js not supported.
Instead change the require of C:\work\Builder\MyProject\node_modules\ansi-regex\index.js in C:\work\Builder\MyProject\node_modules\strip-ansi\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\work\Builder\MyProject\node_modules\strip-ansi\index.js:2:19)
    at Object.<anonymous> (C:\work\Builder\MyProject\node_modules\jest-junit\utils\buildJsonResults.js:3:19)
    at Object.<anonymous> (C:\work\Builder\MyProject\node_modules\jest-junit\index.js:8:26)`

**Comment by palmerj3** [comment]
I suspect this is a local environment issue and not a problem with jest-junit.

Please create a repository that reproduces this issue.

**Comment by alons1** [comment]
Some how this got fixed on it's own..
