### ISSUE TITLE
Failed to write coverage reports:

### ISSUE THREAD

**Issue by ujjainimukherjee** [jest-community/jest-junit#260]
Getting thsi error when running unit tests with jest and typesccript 

ERROR: TypeError: _istanbulReports(...).default.create(...).execute is not a function
        STACK: TypeError: _istanbulReports(...).default.create(...).execute is not a function
    at /Users/umukher/centralprojects/car_central-api/node_modules/@jest/reporters/build/CoverageReporter.js:201:12
    at Array.forEach (<anonymous>)
    at CoverageReporter.onRunComplete (/Users/umukher/centralprojects/car_central-api/node_modules/@jest/reporters/build/CoverageReporter.js:182:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ReporterDispatcher.onRunComplete (/Users/umukher/centralprojects/car_central-api/node_modules/@jest/core/build/ReporterDispatcher.js:71:9)
    at TestScheduler.scheduleTests (/Users/umukher/centralprojects/car_central-api/node_modules/@jest/core/build/TestScheduler.js:306:5)
    at runJest (/Users/umukher/centralprojects/car_central-api/node_modules/@jest/core/build/runJest.js:367:19)
    at _run10000 (/Users/umukher/centralprojects/car_central-api/node_modules/@jest/core/build/cli/index.js:343:7)
    at runCLI (/Users/umukher/centralprojects/car_central-api/node_modules/@jest/core/build/cli/index.js:198:3)
    at Object.run (/Users/umukher/centralprojects/car_central-api/node_modules/jest-cli/build/run.js:124:37)

**Comment by palmerj3** [comment]
This does not appear to be an issue with jest-junit reporter.

But if it is please post a repository that reproduces this issue.

**Comment by sstephant** [comment]
@ujjainimukherjee  I had the exact same issue. 
You may want to check your jest configuration it turns out that my reporters were configured with the `coverageReporters` property in my `package.json` while it should have been the property `reports`.

**Comment by ujjainimukherjee** [comment]
We are not using jest-junit 
collectCoverage: true,
  collectCoverageFrom : [
    "src/**/*.{js,jsx,tsx,ts}",
    "!src/modules/assets/classes/**",
    "!src/modules/templates/**",
    "!src/server.ts",
  ],
  coverageProvider: 'v8',
  coverageReporters: ['clover', 'json', 'lcov', ['text', {skipFull: true}]],
  globals: {
    "ts-jest": {
      "tsconfig": "tsconfig.json",
      "disableSourceMapSupport": true,
      "diagnostics": false,
    }
  }

**Comment by palmerj3** [comment]
If you're not using jest-junit then why are you submitting an issue on the jest-junit repository?

Like I said, I don't see any possible reason why jest-junit would cause this particular error. And I don't see any mention of jest-junit in the config you submitted.

**Comment by mdogadailo** [comment]
Based on the call at `CoverageReporter.js:201:12`, it seems the OP mistakenly added 'jest-junit' to the 'coverageReporters' section in their jest.config. For those who might encounter this in the future, please be careful:

instead of 
```js
{
  coverageReporters: ['jest-junit'],
}
```
Instead, you should specify your configuration as follows:
```js
{
  reports: ['jest-junit'],
}
```
